<a href="https://colab.research.google.com/github/rishabhhgit/matplotlib-seaborne/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

data=[
     ['John', 'Anna', 'Peter', 'Linda'],
     [28, 34, 29, 42],
     ['New York', 'Paris', 'Berlin', 'London'],
     [65000, 70000, 62000, 85000]
]
x = pd.DataFrame(data)
print(x)

          0      1       2       3
0      John   Anna   Peter   Linda
1        28     34      29      42
2  New York  Paris  Berlin  London
3     65000  70000   62000   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns=['name','age','city','salary']
y_1=pd.DataFrame(data_list,columns=columns)
y_1

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
print(y_1[['name','city']])

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [ ]:
data_list1 = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns=['name','age','city','salary']
y_2=pd.DataFrame(data_list1,columns=columns)
y_2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
y_2

    name  age      city  salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [ ]:
import pandas as pd
import numpy as np
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns=['name','age','city','salary']
y_1=pd.DataFrame(data_list,columns=columns)
print(y_1)
y_1.drop('city',axis=1,inplace=True)

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
y_1=y_1.loc[[2,3]] [['name','age']]
y_1

    name  age
2  Peter   29
3  Linda   42

conditional

In [ ]:
import pandas as pd
import numpy as np
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns=['name','age','city','salary']
y_1=pd.DataFrame(data_list,columns=columns)
print(y_1)
y_1.drop('city',axis=1,inplace=True)

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
y_1=y_1[y_1['age']>35]
y_1

    name  age  salary
3  Linda   42   85000

missing data

In [ ]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

x=df.isna()
x

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64